// <auto-generated />
using System;
using FinancialPortfolio.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialPortfolio.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903063732_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.AppUser.AppUserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.HasIndex("UserCode")
                        .IsUnique()
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Etf.EtfDetailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AverageVolume")
                        .HasColumnType("bigint")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("EPS")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<long>("EtfId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("HighPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("LowPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("MarketCap")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("OpenPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("PE")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("PreviousClose")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("PriceChange")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("Week52High")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("Week52Low")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.HasKey("Id");

                    b.HasIndex("EtfId")
                        .IsUnique();

                    b.ToTable("EtfDetails", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Etf.EtfEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("ISINCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.HasKey("Id");

                    b.HasIndex("ISINCode")
                        .IsUnique();

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Etfs", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("Portfolios", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioFixedDepositEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountRef")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("InterestType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("PortfolioId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Principal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("PortfolioFixedDeposits", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioInsurancePolicyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ExpectedMaturityAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InsurerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("PolicyTermYears")
                        .HasColumnType("int");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("PortfolioId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PremiumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PremiumFrequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PremiumPayingTermYears")
                        .HasColumnType("int");

                    b.Property<int>("PremiumsPaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SumAssured")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("PortfolioId", "PolicyNumber")
                        .IsUnique();

                    b.ToTable("PortfolioInsurancePolicies", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioMutualFundEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Amc")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("AverageNav")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentNav")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("FolioNumber")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("InvestedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NavAsOf")
                        .HasColumnType("datetime2");

                    b.Property<string>("NavSource")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("PortfolioId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SchemeCode")
                        .HasColumnType("int");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SchemeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Units")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("PortfolioMutualFunds", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioRecurringDepositEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountRef")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("BankIfsc")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstallmentsPaid")
                        .HasColumnType("int");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("LinkedAccountNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LinkedIfsc")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("PortfolioId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("PortfolioRecurringDeposits", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioRecurringDepositInstallmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromAccountNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FromBankName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FromIfsc")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("PenaltyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("RecurringDepositId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("RecurringDepositId");

                    b.HasIndex("RecurringDepositId", "InstallmentNumber")
                        .IsUnique();

                    b.ToTable("PortfolioRecurringDepositInstallments", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioStockDividendEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DividendDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("PerShareAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("PortfolioId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("StockId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DividendDate");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("StockId");

                    b.HasIndex("PortfolioId", "StockId");

                    b.ToTable("PortfolioStockDividends", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioStockHoldEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("HoldDays")
                        .HasColumnType("bigint");

                    b.Property<string>("HoldNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("InvestmentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsSold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LotStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PortfolioId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<long>("StockId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsSold");

                    b.HasIndex("LotStatus");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("StockId");

                    b.HasIndex("PortfolioId", "IsSold");

                    b.HasIndex("PortfolioId", "LotStatus");

                    b.ToTable("PortfolioStockHolds", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioStockSoldEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("HoldDays")
                        .HasColumnType("bigint");

                    b.Property<string>("LotStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PortfolioStockHoldId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SellPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SellQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("SoldDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoldNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("LotStatus");

                    b.HasIndex("PortfolioStockHoldId");

                    b.HasIndex("SoldDate");

                    b.ToTable("PortfolioStockSolds", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.RefreshToken.RefreshTokenEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Stock.StockDetailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AverageVolume")
                        .HasColumnType("bigint")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("EPS")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("HighPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("LowPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("MarketCap")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("OpenPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("PE")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("PreviousClose")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("PriceChange")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("StockId")
                        .HasColumnType("bigint");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("Week52High")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<decimal>("Week52Low")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.HasKey("Id");

                    b.HasIndex("StockId")
                        .IsUnique();

                    b.ToTable("StockDetails", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Stock.StockEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("ISINCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.HasKey("Id");

                    b.HasIndex("ISINCode")
                        .IsUnique();

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Stocks", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.SystemLog.SystemLogDetailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SystemLogId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SystemLogId")
                        .IsUnique();

                    b.ToTable("SystemLogDetails", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.SystemLog.SystemLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApplicationLevel")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<Guid?>("IdentityUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("MachineName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Searchable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("QueryEngine:Filterable", true)
                        .HasAnnotation("QueryEngine:Sortable", true);

                    b.Property<string>("RequestPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LogLevel");

                    b.HasIndex("UserId");

                    b.ToTable("SystemLogs", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("ApplicationRoleId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.AppUser.AppUserEntity", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Identity.ApplicationUser", "IdentityUser")
                        .WithOne()
                        .HasForeignKey("FinancialPortfolio.Data.Entities.AppUser.AppUserEntity", "IdentityUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Etf.EtfDetailEntity", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Entities.Etf.EtfEntity", "Etf")
                        .WithOne("EtfDetail")
                        .HasForeignKey("FinancialPortfolio.Data.Entities.Etf.EtfDetailEntity", "EtfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etf");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioEntity", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Entities.AppUser.AppUserEntity", "User")
                        .WithOne()
                        .HasForeignKey("FinancialPortfolio.Data.Entities.Portfolio.PortfolioEntity", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioFixedDepositEntity", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Entities.Portfolio.PortfolioEntity", "Portfolio")
                        .WithMany("PortfolioFixedDeposits")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioInsurancePolicyEntity", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Entities.Portfolio.PortfolioEntity", "Portfolio")
                        .WithMany("PortfolioInsurancePolicies")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioMutualFundEntity", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Entities.Portfolio.PortfolioEntity", "Portfolio")
                        .WithMany("PortfolioMutualFunds")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioRecurringDepositEntity", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Entities.Portfolio.PortfolioEntity", "Portfolio")
                        .WithMany("PortfolioRecurringDeposits")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioRecurringDepositInstallmentEntity", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Entities.Portfolio.PortfolioRecurringDepositEntity", "RecurringDeposit")
                        .WithMany("Installments")
                        .HasForeignKey("RecurringDepositId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecurringDeposit");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioStockDividendEntity", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Entities.Portfolio.PortfolioEntity", "Portfolio")
                        .WithMany("PortfolioStockDividends")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialPortfolio.Data.Entities.Stock.StockEntity", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioStockHoldEntity", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Entities.Portfolio.PortfolioEntity", "Portfolio")
                        .WithMany("PortfolioStockHolds")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialPortfolio.Data.Entities.Stock.StockEntity", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioStockSoldEntity", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Entities.Portfolio.PortfolioStockHoldEntity", "PortfolioStockHold")
                        .WithMany("PortfolioStockSolds")
                        .HasForeignKey("PortfolioStockHoldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioStockHold");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.RefreshToken.RefreshTokenEntity", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Identity.ApplicationUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Stock.StockDetailEntity", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Entities.Stock.StockEntity", "Stock")
                        .WithOne("StockDetail")
                        .HasForeignKey("FinancialPortfolio.Data.Entities.Stock.StockDetailEntity", "StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.SystemLog.SystemLogDetailEntity", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Entities.SystemLog.SystemLogEntity", "SystemLog")
                        .WithOne("SystemLogDetail")
                        .HasForeignKey("FinancialPortfolio.Data.Entities.SystemLog.SystemLogDetailEntity", "SystemLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemLog");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Identity.ApplicationRole", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationRoleId");

                    b.HasOne("FinancialPortfolio.Data.Identity.ApplicationUser", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("FinancialPortfolio.Data.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialPortfolio.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FinancialPortfolio.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Etf.EtfEntity", b =>
                {
                    b.Navigation("EtfDetail");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioEntity", b =>
                {
                    b.Navigation("PortfolioFixedDeposits");

                    b.Navigation("PortfolioInsurancePolicies");

                    b.Navigation("PortfolioMutualFunds");

                    b.Navigation("PortfolioRecurringDeposits");

                    b.Navigation("PortfolioStockDividends");

                    b.Navigation("PortfolioStockHolds");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioRecurringDepositEntity", b =>
                {
                    b.Navigation("Installments");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Portfolio.PortfolioStockHoldEntity", b =>
                {
                    b.Navigation("PortfolioStockSolds");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.Stock.StockEntity", b =>
                {
                    b.Navigation("StockDetail");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Entities.SystemLog.SystemLogEntity", b =>
                {
                    b.Navigation("SystemLogDetail");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Identity.ApplicationRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FinancialPortfolio.Data.Identity.ApplicationUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
